version: "2"

checks:
 return-statements:
   enabled: false
 similar-code:
   enabled: false
 identical-code:
   enabled: false
 file-lines:
   enabled: false

exclude_paths:
- "node_modules/"
- "UI/"
- "server/src/tests"
- "server/src/models"
