language: node_js

node_js:
  - '10.1.0'
services:
  - postgresql

env:
  global:
    - CC_TEST_REPORTER_ID=5bba2edcdc6153de5608fb4e61ba72f5388dfc3a9971aced041a14bcc4c87165

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
script:
  - yarn test
  
cache: 
  yarn: true
  directories:
    - 'node_modules'

  before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
after_success:
  - yarn coverage